#pragma ones
#ifndef CONST_DEFINE_H
#define CONST_DEFINE_H

#define LINE_WIDTH 700
#define LINE_HEIGHT 30
#define LINE_GAP 4
#define TEXT_UPPER_BLANK 20
#define TEXT_LEFT_BLANK 30
#define INPUT_LEFT_BLANK 1
#define INPUT_DOWN_BLANK 1
#define WINDOW_HEIGHT 600
#define WINDOW_WIDTH 800

#define ROW_NUMBER 40
#define COLUME_NUMBER 150

#define REFLASH_TIME 20
#define DISPLAY_COUNT 15

#endif // CONST_DEFINE_H
